name: new_klikdna
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_localizations:
    sdk: flutter
  provider: ^4.3.2+2
  crypto: ^2.1.5
  http: ^0.12.2
  alt_http: ^0.3.0
  animated_splash_screen: ^1.0.0+1
  custom_splash: ^0.0.2
  page_transition: ^1.1.7+3
  pin_code_fields: ^5.0.1
  flutter_pin_code_fields: ^1.1.0
  shared_preferences: ^0.5.8
  ##shared_preferences: ^0.4.3
  font_awesome_flutter: ^8.5.0
  carousel_slider: ^2.2.1
  fluttericon: ^1.0.7
  simple_animations: ^1.3.3
  url_launcher: ^5.7.10
  #barcode_scan: ^3.0.1
  barcode_widget: ^1.4.0
  vibration: ^1.2.4
  #connectivity: ^0.4.9+2
  datetime_picker_formfield: ^1.0.0
  flutter_native_image: ^0.0.5+2
  unicorndial: ^1.1.5
  flushbar: ^1.5.0
  image_picker:
  path_provider:
  #sqflite: any
  date_format: ^1.0.8
  intl: ^0.16.1
  dropdownfield: ^1.0.3
  form_field_validator: ^1.0.1
  health: ^2.0.4+1
  fit_kit: ^1.1.2
  loadany: ^0.1.4
  lazy_load_scrollview: ^1.2.0
  english_words: ^3.1.5
  dio: ^3.0.10
  html: ^0.14.0+3
  cached_network_image: ^2.3.1
  ext_storage:
  permission_handler: 5.0.1+2
  json_annotation: ^2.4.0
  flutter_launcher_icons: "^0.7.3"
  flutter_downloader: ^1.5.1
  native_share: ^1.0.0
  wc_flutter_share: ^0.2.2
  share: any
  social_share: ^2.0.5
  flutter_share_me: ^0.9.2
  fluttertoast: ^7.1.5
  achievement_view: ^0.2.1
  charts_flutter: ^0.9.0
  fl_chart: ^0.12.0
  flutter_widget_from_html_core: ^0.5.1+4
  flutter_spinkit: ^4.1.2+1




  #esys_flutter_share: ^1.0.2
#  share:
#    git:
#      url: https://github.com/MperorM/flutter-share.git

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png"


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - languages/id.json
